### ISSUE TITLE
bişi sorucam

### ISSUE THREAD

**Issue by Approval-Denial** [starktwo/v14-Public-Ekip-Bots#1]
kanka bu tantoony nin alt yapısı değil mi

**Comment by starktwo** [comment]
Hocam ne alaka ? Eski ortağım + sıfırdan yazıyoz knk :) gel buyur infernoya yayın açim sana

**Comment by Parzivxll** [comment]
> kanka bu tantoony nin alt yapısı değil mi

baya hakimsin bakıyorum da altyapıya maşallah muhtemelen Tantoony kendisi bu kadar emin bir şekilde soramazdı

**Comment by starktwo** [comment]
Hocam ben bişey demiyorum gelin beraber yazalım ozaman sıfırdan :) öyle discorda bot developer yazmakla olmuyor alanınız neyse orda kapışalım bebişler
