### ISSUE TITLE
Tantoony Bots?

### ISSUE THREAD

**Issue by iawoken** [starktwo/v14-Public-Ekip-Bots#2]
Dostum selam, projeni gördüm ve dosya düzeni ilgimi çekti. Bu düzen **Tantoony** isimli **Yalın** arkadaşımızın leak edilen botlarının dosya düzeninin neredeyse tıpatıp aynısı.

Kodları editleyip veya özenip(benzetip/türetmen) burada star isteyerek bu kodlardan prim kasman hiç hoş değil.
Umarım bir gün seni, kendi yazdığın kodlar ile bu repoda tekrardan görürüm. O zaman bir star da benden alırsın <3

Sevgiler,
Awoken.

**Comment by starktwo** [comment]
Selam Awoken.  

Öncelikle beni tanımamana üzüldüm yılların dostluğu var aramızda paylaşılan projelerde sağ tarafa bakarsan kod ekibinde olduğumu görürsün. Bahsettiğin kişi yani Yalın yıllardır dostluğumu ve ortaklığımı sürdürdüğüm kişidir.

**Comment by starktwo** [comment]
İletişim bilgilerim. 

İG: savastwo
DC: Starkss#0001
